/* 
 * Name: postgres_init.sql
 * Created by: Isaac Lya2
 * Email: ilyatuu@gmail.com
 * Date: Feb 23th, 2023 
 * Purpose: Run this to initialize mysql tables for the va dashboard management app to run.
 * Run this once. This script will reset all tables for the va dashboard management app. 
 * DO NOT RUN this script if there exist data in the dashboard. This is because it will re-set all users and data
 * including va already coded.
 * */


/*
*  Create table structures
**/
CREATE TABLE IF NOT EXISTS _web_assignment
(
    va_uri character varying(80) COLLATE pg_catalog."default",
    coder1_assigned_date timestamp without time zone,
    coder1_completed_date timestamp without time zone,
    coder1_coda integer,
    coder1_codb integer,
    coder1_codc integer,
    coder1_codd integer,
    coder2_assigned_date timestamp without time zone,
    coder2_completed_date timestamp without time zone,
    coder2_coda integer,
    coder2_codb integer,
    coder2_codc integer,
    coder2_codd integer,
    coder1_comments character varying COLLATE pg_catalog."default",
    coder2_comments character varying COLLATE pg_catalog."default",
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    coder1_id integer,
    coder2_id integer,
    va_table character varying(80) COLLATE pg_catalog."default",
    CONSTRAINT assignment_primary_key PRIMARY KEY (id),
    CONSTRAINT unique_uri UNIQUE (va_uri)
);

CREATE TABLE IF NOT EXISTS _web_forms
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    form_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    form_odk_table character varying(50) COLLATE pg_catalog."default" NOT NULL,
    form_details character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT _web_forms_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS _web_roles
(
    roleid integer NOT NULL,
    rolename character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT _unique_role_id PRIMARY KEY (roleid)
);

CREATE TABLE IF NOT EXISTS _web_users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    username character varying(50) COLLATE pg_catalog."default",
    fullname character varying(50) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    loginsession character varying(255) COLLATE pg_catalog."default",
    lastlogin timestamp without time zone,
    phone character varying(25) COLLATE pg_catalog."default",
    roleid integer,
    organization character varying(25) COLLATE pg_catalog."default",
    api_key character varying COLLATE pg_catalog."default",
    isActive integer DEFAULT '1',
    CONSTRAINT _web_users_pkey PRIMARY KEY (id),
    CONSTRAINT _web_users_username UNIQUE (username),
    CONSTRAINT _web_users_roles FOREIGN KEY (roleid)
        REFERENCES _web_roles (roleid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS _web_messages
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    msg_from integer,
    msg_to integer,
    msg_date time without time zone,
    msg_text character varying COLLATE pg_catalog."default",
    msg_va character varying(80) COLLATE pg_catalog."default",
    CONSTRAINT message_unique_id PRIMARY KEY (id),
    CONSTRAINT message_from_user FOREIGN KEY (msg_from)
        REFERENCES _web_users (id) MATCH SIMPLE
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT message_to_user FOREIGN KEY (msg_to)
        REFERENCES _web_users (id) MATCH SIMPLE
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS _web_form_users
(
    form_id integer NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT web_form_users_pk PRIMARY KEY (form_id, user_id),
    CONSTRAINT _web_form_forms FOREIGN KEY (form_id)
        REFERENCES _web_forms (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT _web_form_users FOREIGN KEY (user_id)
        REFERENCES _web_users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS _web_icd10_category
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT category_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS _web_icd10
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    icdcode character varying(25) COLLATE pg_catalog."default",
    icdname character varying(255) COLLATE pg_catalog."default",
    category_id integer,
    CONSTRAINT primary_key_icd10 PRIMARY KEY (id),
    CONSTRAINT icd10_category FOREIGN KEY (category_id)
        REFERENCES _web_icd10_category (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

/*
*  Insert default data
**/
INSERT INTO _web_roles(roleid,rolename) VALUES 
(0,'Read Only'),(1,'Data Manager'),(2,'Coder'),(3,'Administrator'),(4,'Mobile User');

INSERT INTO _web_users (username,fullname,password,phone,roleid,organization,api_key)
VALUES ('admin','Administrator',md5('welcome2vman'),'0678556677',3,'MoH',123456);

INSERT INTO _web_icd10_category(name) VALUES
('Communicable or notifiable diseases'),
('Trauma and Injury'),
('Non Communicable Diseases'),
('Gastro Intestinal Track'),
('Neonatal Conditions'),
('Maternal Deaths'),
('Toxic effects of substances chiefly non medicinal '),
('Poisoning by drugs, medicaments and biological sub'),
('Burns and corrosion of multiple and unspecified bo'),
('Other and unspecified effects of exgternal causes'),
('Complications of surgical and medical care, not el'),
('Assault'),
('Transport accidents'),
('Others');

INSERT INTO _web_icd10(icdcode,icdname,category_id) VALUES
('A00', 'Cholera', 1),
('A01', 'Typhoid', 1),
('A20', 'Plague', 1),
('A33', 'Tetanus, Neonatal', 1),
('A41', 'Septicaemia', 1),
('A75', 'Relapsing Fever (Louse borne Typhus)', 1),
('B05', 'Measles', 1),
('B45', 'Meningitis Cryptococal', 1),
('B53', 'Malaria confirmed', 1),
('B54', 'Malaria presumptive', 1),
('C80', 'Neoplasm', 1),
('G03', 'Meningitis', 1),
('G04', 'Encephalitis', 1),
('G83', 'Acute Flaccid Paralysis', 1),
('I50', 'Heart failure', 1),
('J06', 'Respiratory Infection Acute (ARI)', 1),
('J18', 'Pneumonia', 1),
('J45', 'Asthma', 1),
('J81', 'Pulmonary oedema', 1),
('J98', 'Pneumopathies', 1),
('L08', 'Skin infections', 1),
('R09', 'Pleurisy (non-Tuberculosis)', 1),
('R50', 'Fever Chronic (> 1 month)', 1),
('S09', 'Head injury', 2),
('S36', 'Ruptured spleen', 2),
('T14', 'Fractures', 2),
('T14.9', 'Trauma Other', 2),
('T30', 'Burns', 2),
('C46', 'Kaposi''s sarcoma', 3),
('C80', 'Tumours Other malignant', 3),
('D48', 'Tumours Other non-malignant', 3),
('E14', 'Diabetes', 3),
('I42', 'Cardiomyopathy', 3),
('A80', 'Acute Flacid Paralysis (polio)', 4),
('K25', 'Ulcer, gastro-duodenal', 4),
('K46', 'Hernia', 4),
('K65', 'Peritonitis (non-Tuberculosis)', 4),
('K74', 'Cirrhosis of the liver', 4),
('K75', 'Hepatitis', 4),
('K92', 'Digestive tract Haemorrhages', 4),
('M86', 'Bone infections (including osteomyelitis)', 4),
('M89', 'Bone and joint disease other', 4),
('N04', 'Nephrotic syndrome', 4),
('N05', 'Glomerulonephritis', 4),
('N15', 'Kidney infections', 4),
('N39', 'Urinary tract infections', 4),
('N94', 'Gynecological problems', 4),
('B24', 'Paediatric AIDS', 5),
('P15', 'Birth trauma', 5),
('P21', 'Neonatal Asphyxia', 5),
('P54', 'Haemorrhage', 5),
('P74', 'Dehydration', 5),
('P95', 'Stillbirth (macerated)', 5),
('P95', 'Stillbirth', 5),
('Q05', 'Congenital hydrocephalus and spinal bifida', 5),
('Q24', 'Congenital malformation of the heart', 5),
('Q89', 'Other congenital malformation', 5),
('R95', 'Sudden infant death syndrome', 5),
('X49', 'Accidental poisoning by and exposure to noxious substances', 5),
('Y09', 'Assault', 5),
('O06', 'Abortion', 6),
('O46', 'Antepartum Haemorrhage', 6),
('O66', 'Obstructed Labour', 6),
('O71', 'Rupture uterus', 6),
('O72', 'Post-partum haemorrhage', 6),
('O75', 'Local herbs', 6),
('O85', 'Puerperal Sepsis /Septicaemia', 6),
('O99', 'Pneumonia', 6),
('Z21', 'Asymptomatic HIV', 6),
('T29', 'Burns and corrosions of multiple body regions', 7),
('T30', 'Burn and corrosion, body region unspecified', 7),
('T31', 'Burns classified according to extent of body surface involved', 7),
('T32', 'Corrosions classified according to extent of body surface involved', 7),
('T50', 'Poisoning by diuretics and other unspecified drugs, medicaments and biological substances', 8),
('T51', 'Toxic effect of alcohol', 9),
('T54', 'Toxic effect of corrosive substances', 9),
('T56', 'Toxic effect of metals', 9),
('T58', 'Toxic effect of carbon monoxide', 9),
('T59', 'Toxic effect of other gases, fumes and vapours', 9),
('T60', 'Toxic effect of pesticides', 9),
('T65', 'Toxic effect of other and unspecified substances', 9),
('T67', 'Effects of heat and light', 10),
('T70', 'Effects of air pressure and water pressure', 10),
('T71', 'Asphyxiation', 10),
('T80', 'Complications following infusion, transfusion and therapeutic injection', 11),
('T81', 'Complications of procedures, not elsewhere classified', 11),
('T83', 'Complications of genitourinary devices, implants and grafts', 11),
('Y08', 'Assault by other specified means', 12),
('Y09', 'Assault by other unspecified means', 12),
('V98', 'Other Specified transport accidents', 13),
('V99', 'Unspecified transport accidents', 13),
('P78', 'Diarrhoea - Perinatal digestive system disorders', 5),
('N19', 'Unspecified kidney failure', 14),
('D64', 'Other anemias', 14),
('E46', 'Unspecified protein-calorie malnutrition', 14),
('I51', 'Complications and ill-defined descriptions of heart disease', 14),
('B24', 'Other and unspecified HIV disease', 1),
('A06', 'Amoebiasis', 1),
('A16', 'Respiratory tuberculosis, not confirmed bacteriologically or histologically', 1),
('C50', 'Malignant neoplasm of breast', 3),
('K37', 'Appendicitis', 4),
('C55', 'Malignant neoplasm of uterus, part unspecified', 3),
('C61', 'Malignant neoplasm of prostate', 3),
('I64', 'Stroke, not specified as haemorrhage or infarction', 3),
('K29', 'Gastritis and duodenitis', 4),
('O75', 'Other complication of labour and delivery not else classified', 6),
('O16', 'Unspecified maternal hypertension', 6),
('O99', 'Other maternal diseases complicating pregnancy, child birth and puerperium', 6),
('P05', 'Low birth weight', 5),
('P22', 'Respiratory distress of newborn', 5),
('P36', 'Bacterial diseases of newborn [neonatal sepsis]', 5),
('P37', 'Congenital malaria', 5),
('I11', 'Hypertensive heart disease', 14),
('R99', 'Ill-defined and unknown cause of mortality', 14),
('E40', 'Kwashiorkor', 14),
('W01', 'Fall on same level from slipping, tripping and stumbling', 2),
('W17', 'Other fall from one level to another', 2),
('W74', 'Unspecified cause of accidental drowning and submersion', 2),
('D57', 'Sickle-cell disorders', 3),
('O99.4', 'Diseases of the circulatory system complicating pregnancy, childbirth and the puerperium', 6),
('P23', 'Congenital pneumonia', 5),
('G40', 'Epilepsy', 3),
('W14', 'Fall from a tree', 2),
('W20', 'Struck by thrown, projected or falling object', 2),
('K86', 'Disease of pancreas, unspecified', 3),
('F32', 'Depression', 3),
('W19', 'Unspecified fall', 2),
('X83', 'Intentional Self-harm by other specified means', 2),
('X84', 'Intentional Self-harm by unspecified means', 2),
('X33', 'Victim of Lightning', 10),
('A97', 'Dengue', 1),
('X27', 'Contact with other specified  venomous animals', 10),
('J44', 'Chronic Obstructive Pulmonary Disease', 1),
('W55', 'Bitten or struck by other mammals', 10),
('X08', 'Exposure to other specified smoke, fire and flames', 7),
('W79', 'Inhalation and ingestion of food causing obstruction of respiratory', 14),
('A01', 'Typhoid and paratyphoid', 1),
('A09', 'Other and unspecified diarrhoeal diseases', 1),
('A15', 'Respiratory tuberculosis, confirmed bacteriologically or histologically', 1),
('C22', 'Malignant neoplasm of liver and intrahepatic bile ducts', 3),
('C53', 'Malignant neoplasm of cervix uteri', 3),
('I10', 'Essential (primary) hypertension', 3),
('K56', 'Paralytic ileus and intestinal obstruction without hernia [Intussusception & volvulus]', 4),
('K76', 'Other unspecified liver diseases', 3),
('O98', 'Maternal infectious and parasitic diseases complicating pregnancy, child birth and puerperium', 6),
('P95', 'Fetal death of unspecified cause [stillbirth]', 5),
('A03', 'Shigellosis', 14),
('A09.0', 'Other and unspecified diarrhoeal diseases', 14),
('A17', 'Tuberculosis of nervous system', 14),
('A18', 'Tuberculosis of other organs', 14),
('A19', 'Miliary tuberculosis', 14),
('A22', 'Anthrax', 14),
('A23', 'Brucellosis', 14),
('A30', 'Leprosy', 14),
('A34', 'Obstetric tetanus', 14),
('A36', 'Diphtheria', 14),
('A37', 'Whooping cough', 14),
('A39', 'Meningococcal infection', 14),
('A40', 'Streptococcal sepsis', 14),
('A50', 'Congenital syphilis', 14),
('A51', 'Syphilis (early)', 14),
('A64', 'Other and unspecified infections with a predominantly sexual mode of transmission', 14),
('A68', 'Relapsing fever', 14),
('A82', 'Rabies', 14),
('A87', 'Viral meningitis', 14),
('A95', 'Yellow fever', 14),
('A98', 'Other viral haemorrhagic fevers', 14),
('B00', 'Herpes viral [herpes simples]', 14),
('B01', 'Varicella [chicken pox]', 14),
('B02', 'Zoster [herpes zoster]', 14),
('B06', 'Rubella (German measles]', 14),
('B16', 'Hepatitis B', 14),
('B17', 'Other viral hepatitis', 14),
('B19', 'Unspecified viral hepatitis', 14),
('B20', 'HIV disease with tuberculosis', 14),
('B21', 'HIV disease resulting in malignant neoplasm', 14),
('B22', 'HIV disease resulting in other specified diseases', 14),
('B37', 'Candidiasis', 14),
('B55', 'Leishmaniasis', 14),
('B56', 'African trypanosomiasis', 14),
('B57', 'Chagas disease', 14),
('B58', 'Toxoplasmosis', 14),
('B59', 'Pneumocystosis [PCP]', 14),
('B65', 'Schistosomiasis', 14),
('C03', 'Malignant neoplasm of the gum', 14),
('C14', 'Malignant neoplasm of other and ill-defined sites in the lip, oral cavity and pharynx', 14),
('C15', 'Malignant neoplasm of Oesophagus', 14),
('C16', 'Malignant neoplasm of stomach', 14),
('C17', 'Malignant neoplasm of small intestine', 14),
('C18', 'Malignant neoplasm of colon', 14),
('C20', 'Malignant neoplasm of rectum', 14),
('C25', 'Malignant neoplasm of pancrease', 14),
('C30', 'Malignant neoplasm of nasal cavity and middle ear', 14),
('C32', 'Malignant neoplasm of larynx', 14),
('C33', 'Malignant neoplasm of trachea', 14),
('C34', 'Malignant neoplasm of bronchus and lung', 14),
('C43', 'Malignant melanoma of skin', 14),
('C52', 'Malignant neoplasm of vagina', 14),
('C56', 'Malignant neoplasm of ovary', 14),
('C58', 'Malignant neoplasm of placenta [choriocarcinoma]', 14),
('C60', 'Malignant neoplasm of penis', 14),
('C64', 'Malignant neoplasm of kidney', 14),
('C67', 'Malignant neoplasm of bladder', 14),
('C69', 'Malignant neoplasm of eye and adnexa', 14),
('C70', 'Malignant neoplasm of meninges', 14),
('C71', 'Malignant neoplasm of brain', 14),
('C76', 'Malignant neoplasm of other and ill-defined sites', 14),
('C81', 'Hodgkin lymphoma', 14),
('C85', 'Other and unspecified types of non-Hodgkin lymphoma', 14),
('C90', 'Multiple myeloma and malignant plasma cell neoplasms', 14),
('C91', 'Lymphoid leukemia', 14),
('C92', 'Myeloid leukemia', 14),
('C93', 'Monocytic leukemia', 14),
('C94', 'Other leukemias of specified cell type', 14),
('C95', 'Leukemia of unspecified cell type', 14),
('D50', 'Iron deficiency anaemia', 14),
('D52', 'Folate deficiency anaemia', 14),
('D65', 'Disseminated intravascular coagulation [defibrination syndrome]', 14),
('D68', 'Other coagulation defects [incl. Vit. K deficiency]', 14),
('E05', 'Thyrotoxicosis [hyperthyroidism]', 14),
('E10', 'Type 1 diabetes mellitus', 14),
('E11', 'Type 2 diabetes mellitus', 14),
('E41', 'Nutritional marasmus', 14),
('E42', 'Marasmic - kwashiorkor', 14),
('E51', 'Thiamine deficiency', 14),
('E86', 'Volume depletion [dehydration]', 14),
('F01', 'Vascular dementia', 14),
('F05', 'Delirium, not induced by alcohol and other psychoactive substances', 14),
('F10', 'Alcohol use disorders', 14),
('F11', 'Mental and behavioural disorders due to use of opioids', 14),
('F13', 'Mental and behavioural disorders due to use of sedatives or hypnotics', 14),
('F14', 'Mental and behavioural disorders due to use of cocaine', 14),
('F19', 'Mental and behavioural disorders due to multiple drug use and use of other psychoactive substances', 14),
('G00', 'Bacterial meningitis', 14),
('G06', 'Intracranial and intraspinal abscess and granuloma', 14),
('G30', 'Alzheimers disease, dementias', 14),
('H66', 'Suppurative and unspecified otitis media', 14),
('I05', 'Rheumatic mitral valve diseases', 14),
('I15', 'Secondary hypertension', 14),
('I20', 'Angina pectoris', 14),
('I21', 'Acute myocardial infarction', 14),
('I24', 'Other acute ischaemic heart diseases', 14),
('I26', 'Pulmonary embolism', 14),
('I30', 'Acute pericarditis', 14),
('I38', 'Endocarditis', 14),
('I42', 'Cardiomyopathy', 14),
('I60', 'Subarachnoid haemorrhage', 14),
('I61', 'lntracerebral haemorrhage', 14),
('I63', 'Cerebralinfarction', 14),
('I69', 'Sequelae of cerebrovascular disease', 14),
('I70', 'Atherosclerosis', 14),
('I71', 'Aortic aneurism and dissection', 14),
('I74', 'Arterial embolism and thrombosis', 14),
('I85', 'Oesophageal varices', 14),
('J03', 'Acute tonsillitis', 14),
('J05', 'Acute obstructive laryngitis [croup] and epiglottitis', 14),
('J11', 'Influenza', 14),
('J21', 'Acute bronchiolitis', 14),
('J36', 'Peritonsillar abscess [Quinsy]', 14),
('J40', 'Bronchitis', 14),
('J47', 'Bronchiectasis', 14),
('J64', 'Pneumoconiosis', 14),
('J68', 'Respiratory conditions due to inhalation of chemicals, gases, fumes and vapours [chemical bronchitis]', 14),
('J85', 'Abscess of lung and mediastinum', 14),
('J90', 'Pleural effusion', 14),
('J93', 'Pneumothorax', 14),
('K02', 'Dental caries', 14),
('K04', 'Disease of pulp and periapical tissues [dental abscess]', 14),
('K20', 'Oesophagitis', 14),
('K26', 'Duodenal ulcer', 14),
('K27', 'Peptic ulcer, site unspecified', 14),
('K35', 'Acute appendicitis', 14),
('K36', 'Other appendicitis', 14),
('K40', 'Inguinal hernia', 14),
('K41', 'Femoral hernia', 14),
('K42', 'Umbilical hernia', 14),
('K70', 'Alcoholic liver disease', 14),
('K71', 'Toxic liver disease', 14),
('K72', 'Hepatic failure [encephalopathy]', 14),
('K85', 'Acute pancreatitis', 14),
('L88', 'Pyoderma gangrenosum', 14),
('L89', 'Decubitus ulcer and pressure area', 14),
('L98', 'Other disorders of skin and subcutaneous tissues', 14),
('M60', 'Myositis [pyomyositis]', 14),
('N17', 'Acute renal failure', 14),
('N18', 'Chronic kidney disease [chronic renal failure]', 14),
('N28', 'Other disorders of kidney and ureters', 14),
('N40', 'Hyperplasia of prostate [BPH]', 14),
('O00', 'Ectopic pregnancy', 14),
('O03', 'Spontaneous abortion', 14),
('O04', 'Medical abortion', 14),
('O07', 'Failed attempted abortion [criminal]', 14),
('O10', 'Pre-existing hypertension complicating pregnancy, child birth and the puerperium', 14),
('O13', 'Gestation [pregnancy-induced] hypertension', 14),
('O15', 'Eclampsia', 14),
('O16', 'Unspecified maternal hypertension', 14),
('O24', 'Diabetes mellitus in pregnancy', 14),
('O29', 'Complication of anaesthesia during pregnancy', 14),
('O44', 'Placenta praevia', 14),
('O45', 'Abruptio placenta', 14),
('O64', 'Obstructed labour due to malposition and malpresentation of fetus', 14),
('O65', 'Obstructed labour due to maternal pelvic abnormality', 14),
('O73', 'Retained placenta and membrane without haemorrhage', 14),
('O88', 'Obstetric embolism', 14),
('O95', 'Obstetric death of unspecified cause', 14),
('O96', 'Death from any obstetric cause occurring more than 42 days but less than 1 year after delivery', 14),
('O97', 'Death from sequelae of obstetric causes', 14),
('P00', 'Fetus and newborn affected by maternal conditions that may be unrelated to present pregnancy', 14),
('P02', 'Fetus and newborn affected by complications of placenta, cord and membranes', 14),
('P03', 'Fetus and newborn affected by other complications of labour and delivery', 14),
('P07', 'Disorders relating to short gestation and low birth weight [prematurity]', 14),
('P08', 'Disorders relating to long gestation and high birth weight [post-maturity]', 14),
('P10', 'Intracranial laceration and haemorrhage due to birth injury', 14),
('P24', 'Neonatal aspiration syndromes', 14),
('P38', 'Omphalitis of newborn with or without mild haemorrhage', 14),
('P51', 'Umbilical haemorrhage of newborn', 14),
('P53', 'Haemorrhagic disease of fetus and newborn [Vitamin K deficiency]', 14),
('P55', 'Haemolytic disease of fetus and newborn', 14),
('P57', 'Kernicterus', 14),
('P59', 'Neonatal jaundice from other and unspecified causes', 14),
('P60', 'Disseminated intravascular coagulation of fetus and newborn', 14),
('P80', 'Hypothermia of newborn', 14),
('P96', 'Other conditions originating in the perinatal period', 14),
('Q00', 'Anencephaly and similar malformation', 14),
('Q01', 'Encephalocele', 14),
('Q02', 'Microcephaly', 14),
('Q03', 'Congenital hydrocephalus', 14),
('Q20', 'Congenital malformation of cardiac chambers and connections', 14),
('Q21', 'Congenital malformation of cardiac septa', 14),
('Q22', 'Congenital malformation of pulmonary and tricuspid valves', 14),
('Q23', 'Congenital malformation of aortic and mitral valves', 14),
('Q25', 'Congenital malformation of great arteries', 14),
('Q39', 'Congenital malformation of oesophagus', 14),
('Q42', 'Congenital absence, atresia and stenosis of large intestine', 14),
('Q90', 'Down syndrome', 14),
('R54', 'Senility', 14),
('R57', 'Shock [cardiogenic, hypovolemic and septic]', 14),
('R58', 'Haemorrhage', 14),
('R65', 'Systemic inflammatory response syndrome [SIRS]', 14),
('R96', 'Sudden death (cause unknown)', 14),
('R98', 'Unattended death (found dead and no cause could be discovered)', 14),
('V01', 'Pedestrian injured in collision with pedal cycle', 14),
('V02', 'Pedestrian injured in collision with two or three wheeled motor vehicle', 14),
('V03', 'Pedestrian injured in collision with car, pick-up truck or van', 14),
('V04', 'Pedestrian injured in collision with heavy transport vehicle or bus', 14),
('V05', 'Pedestrian injured in collision with railway train or railway vehicle', 14),
('V06', 'Pedestrian injured in collision with other non-motor vehicle', 14),
('V08', 'Pedestrian injured in other and unspecified traffic accidents', 14),
('V10', 'Pedal cyclist injured in collision with pedestrian or animal', 14),
('V11', 'Pedal cyclist injured in collision with other pedal cycle', 14),
('V12', 'Pedal cyclist injured in collision with two or three wheeled motor vehicle', 14),
('V13', 'Pedal cyclist injured in collision with car, pick-up truck or van', 14),
('V14', 'Pedal cyclist injured in collision with heavy transport vehicle or bus', 14),
('V15', 'Pedal cyclist injured in collision with railway train or railway vehicle', 14),
('V16', 'Pedal cyclist injured in collision with other non-motor vehicle', 14),
('V17', 'Pedal cyclist injured in collision with fixed or stationary object', 14),
('V18', 'Pedal cyclist injured in non-collision transport accident', 14),
('V19', 'Pedal cyclist injured in other and unspecified transport accidents', 14),
('V20', 'Motorcycle rider injured in collision with pedestrian or animal', 14),
('V21', 'Motorcycle rider injured in collision with pedal cycle', 14),
('V22', 'Motorcycle rider injured in collision with two or three wheeled motor vehicle', 14),
('V23', 'Motorcycle rider injured in collision with car, pick-up truck or van', 14),
('V24', 'Motorcycle rider injured in collision with heavy transport vehicle or bus', 14),
('V25', 'Motorcycle rider injured in collision with railway train or railway vehicle', 14),
('V26', 'Motorcycle rider injured in collision with other non-motor vehicle', 14),
('V27', 'Motorcycle rider injured in collision with fixed or stationary object', 14),
('V28', 'Motorcycle rider injured in non-collision transport accident', 14),
('V29', 'Motorcycle rider injured in other and unspecified transport accidents', 14),
('V30', 'Occupant of three wheeled motor vehicle injured in collision with pedestrian or animal', 14),
('V31', 'Occupant of three wheeled motor vehicle injured in collision with pedal cycle', 14),
('V32', 'Occupant of three wheeled motor vehicle injured in collision with two or three wheeled motor vehicle', 14),
('V33', 'Occupant of three wheeled motor vehicle injured in collision with car, pick-up truck or van', 14),
('V34', 'Occupant of three wheeled motor vehicle injured in collision with heavy transport vehicle or bus', 14),
('V35', 'Occupant of three wheeled motor vehicle injured in collision with railway train or railway vehicle', 14),
('V36', 'Occupant of three wheeled motor vehicle injured in collision with other non-motor vehicle', 14),
('V37', 'Occupant of three wheeled motor vehicle injured in collision with fixed or stationary object', 14),
('V38', 'Occupant of three wheeled motor vehicle injured in non-collision transport accidents', 14),
('V39', 'Occupant of three wheeled motor vehicle injured in other and unspecified transport accidents', 14),
('V40', 'Car occupant injured in collision with pedestrian or animal', 14),
('V41', 'Car occupant injured in collision with pedal cycle', 14),
('V42', 'Car occupant injured in collision with two or three wheeled motor vehicle', 14),
('V43', 'Car occupant injured in collision with car, pick-up truck or van', 14),
('V44', 'Car occupant injured in collision with heavy transport vehicle or bus', 14),
('V45', 'Car occupant injured in collision with railway train or railway vehicle', 14),
('V46', 'Car occupant injured in collision with other non-motor vehicle', 14),
('V47', 'Car occupant injured in collision with fixed or stationary object', 14),
('V48', 'Car occupant injured in non-collision transport accidents', 14),
('V49', 'Car occupant injured in collision in other and unspecified transport accidents', 14),
('V50', 'Occupant of pick-up truck or van injured in collision with pedestrian or animal', 14),
('V51', 'Occupant of pick-up truck or van injured in collision with pedal cycle', 14),
('V52', 'Occupant of pick-up truck or van injured in collision with two or three wheeled motor vehicle', 14),
('V53', 'Occupant of pick-up truck or van injured in collision with car, pick-up truck or van', 14),
('V54', 'Occupant of pick-up truck or van injured in collision with heavy transport vehicle or bus', 14),
('V55', 'Occupant of pick-up truck or van injured in collision with railway train or railway vehicle', 14),
('V56', 'Occupant of pick-up truck or van injured in collision with other non-motor vehicle', 14),
('V57', 'Occupant of pick-up truck or van injured in collision with fixed or stationary object', 14),
('V58', 'Occupant of pick-up truck or van injured in non-collision transport accidents', 14),
('V59', 'Occupant of pick-up truck or van injured in other and unspecified transport accidents', 14),
('V60', 'Occupant of heavy transport vehicle injured in collision with pedestrian or animal', 14),
('X65', 'Intentional self-poisoning by and exposure to alcohol', 14),
('V61', 'Occupant of heavy transport vehicle injured in collision with pedal cycle', 14),
('V62', 'Occupant of heavy transport vehicle injured in collision with two or three wheeled motor vehicle', 14),
('V63', 'Occupant of heavy transport vehicle injured in collision with car, pick-up truck or van', 14),
('V64', 'Occupant of heavy transport vehicle injured in collision with heavy transport vehicle or bus', 14),
('V65', 'Occupant of heavy transport vehicle injured in collision with railway train or railway vehicle', 14),
('V66', 'Occupant of heavy transport vehicle injured in collision with other non-motor vehicle', 14),
('V67', 'Occupant of heavy transport vehicle injured in collision with fixed or stationary object', 14),
('V68', 'Occupant of heavy transport vehicle injured in non-collision transport accidents', 14),
('V69', 'Occupant of heavy transport vehicle injured in other and unspecified transport accidents', 14),
('V70', 'Bus occupant injured in collision with pedestrian or animal', 14),
('V71', 'Bus occupant injured in collision with pedal cycle', 14),
('V72', 'Bus occupant injured in collision with two or three wheeled motor vehicle', 14),
('V73', 'Bus occupant injured in collision with car, pick-up truck or van', 14),
('V74', 'Bus occupant injured in collision with heavy transport vehicle or bus', 14),
('V75', 'Bus occupant injured in collision with railway train or railway vehicle', 14),
('V76', 'Bus occupant injured in collision with other non-motor vehicle', 14),
('V77', 'Bus occupant injured in collision with fixed or stationary object', 14),
('V78', 'Bus occupant injured in non-collision transport accidents', 14),
('V79', 'Bus occupant injured in collision in other and unspecified transport accidents', 14),
('V80', 'Animal-rider or occupant of animal ódrawn vehicle injured in transport accident', 14),
('V81', 'Occupant of railway train or railway vehicle injured in transport accident', 14),
('V87', 'Traffic accident of specified type but victims mode of transport unknown', 14),
('V89', 'Motor or non-motor vehicle accident, type of vehicle unspecified', 14),
('V90', 'Accident to watercraft causing drowning and submersion', 14),
('V92', 'Water-transport-related drowning and submersion without accident to watercraft', 14),
('V93', 'Accident on board watercraft without accident to watercraft, not causing drowning and submersion', 14),
('V94', 'Other and unspecified water transport accidents', 14),
('V95', 'Accident to powered aircraft causing injury to occupant', 14),
('W03', 'Other fall on same level due to collision with, or pushing by, another person', 14),
('W04', 'Fall while being carried or supported by other persons', 14),
('W08', 'Fall involving other furniture', 14),
('W10', 'Fall on and from stairs and steps', 14),
('W11', 'Fall on and from ladder', 14),
('W12', 'Fall on and from scaffolding', 14),
('W13', 'Fall from, out of or through building or structure', 14),
('W16', 'Driving or jumping into water causing injury other than drowning or submersion', 14),
('W18', 'Other fall on same level', 14),
('W22', 'Striking against or struck by other object', 14),
('W26', 'Contact with sharp objects', 14),
('W32', 'Handgun discharge [accidental]', 14),
('W34', 'Discharge from other and unspecified firearm [accidental]', 14),
('W54', 'Bitten or struck by dog', 14),
('W58', 'Bitten and struck by crocodile or alligator', 14),
('W65', 'Drowning and submersion while in bath-tub', 14),
('W66', 'Drowning and submersion following fall into bath-tub', 14),
('W67', 'Drowning and submersion while in swimming-pool', 14),
('W68', 'Drowning and submersion following fall into swimming-pool', 14),
('W69', 'Drowning and submersion while in natural water', 14),
('W70', 'Drowning and submersion following fall into natural water', 14),
('W75', 'Accidental suffocation and strangulation in bed', 14),
('W76', 'Other accidental hanging and strangulation', 14),
('W80', 'Inhalation and ingestion of other object causing obstruction of respiratory tract.', 14),
('W81', 'Confined to or trapped in a low oxygen environment', 14),
('W83', 'Other specified threats to breathing', 14),
('W84', 'Unspecified threat to breathing', 14),
('W85', 'Exposure to electric transmission lines [accidental]', 14),
('W86', 'Exposure to other specified electric current [accidental]', 14),
('W87', 'Exposure to unspecified electric current [accidental]', 14),
('W94', 'Exposure to high and low air pressure and changes in air pressure', 14),
('WO1', 'Fall on the same level from slipping, tripling and stumbling', 14),
('X00', 'Exposure to uncontrolled fire in building or structure', 14),
('X01', 'Exposure to uncontrolled fire, not in building or structure', 14),
('X09', 'Exposure to unspecified smoke, fire and flames', 14),
('X10', 'Contact with hot drinks, food, fats and cooking oils', 14),
('X12', 'Contact with other hot fluids, e.g. boiled water', 14),
('X16', 'Contact with hot heating appliances, radiators and pipes', 14),
('X20', 'Contact with venomous snakes and lizards', 14),
('X23', 'Contact with hornets, wasps and bees', 14),
('X26', 'Contact with venomous marine animals and plants', 14),
('X28', 'Contact with other specified venomous plants', 14),
('X29', 'Contact with unspecified venomous animals or plants', 14),
('X34', 'Victim of earthquake', 14),
('X36', 'Victim of landslide and other earth movements', 14),
('X37', 'Victim of cataclysmic [cyclone, hurricane] storm', 14),
('X38', 'Victim of flood', 14),
('X39', 'Exposure to other and unspecified forces of nature', 14),
('X44', 'Accidental poisoning by and exposure to other and unspecified drugs, medicaments and biological substances', 14),
('X45', 'Accidental poisoning by and exposure to alcohol', 14),
('X48', 'Accidental poisoning by and exposure to pesticides', 14),
('X64', 'Intentional self-poisoning by and exposure to other and unspecified drugs, medicaments and biological substances', 14),
('X68', 'Intentional self-poisoning by and exposure to pesticides', 14),
('X69', 'Intentional self-poisoning by and exposure to other and unspecified chemicals and noxious substances', 14),
('X70', 'Intentional self-harm by hanging, strangulation and suffocation', 14),
('X71', 'Intentional self-harm by drowning and submersion', 14),
('X72', 'Intentional self-harm by handgun discharge', 14),
('X74', 'Intentional self-harm by other and unspecified firearm discharge', 14),
('X75', 'Intentional self-harm by explosive material', 14),
('X76', 'Intentional self-harm by smoke, fire and flames', 14),
('X78', 'Intentional self-harm by sharp object', 14),
('X80', 'Intentional self-harm by jumping from a high place', 14),
('X81', 'Intentional self-harm by jumping or lying before moving object', 14),
('X82', 'Intentional self-harm by crushing of motor vehicle', 14),
('X85', 'Assaulted by drugs, medicaments and biological substances', 14),
('X86', 'Assaulted by corrosive substance', 14),
('X87', 'Assaulted by pesticides', 14),
('X90', 'Assaulted by unspecified chemical or noxious substance', 14),
('X91', 'Assaulted by hanging, strangulation and suffocation', 14),
('X92', 'Assaulted by drowning and submersion', 14),
('X93', 'Assaulted by handgun discharge', 14),
('X95', 'Assaulted by other and unspecified firearm discharge', 14),
('X96', 'Assaulted by explosive material', 14),
('X97', 'Assaulted by smoke, fire and flames', 14),
('X99', 'Assaulted by sharp object', 14),
('Y00', 'Assaulted by blunt object', 14),
('Y01', 'Assaulted by pushing from high place', 14),
('Y02', 'Assaulted by pushing or placing victim before moving object', 14),
('Y03', 'Assaulted by crashing of motor vehicle', 14),
('Y05', 'Sexual assault by bodily force [rape]', 14),
('Y06', 'Neglect and abandonment', 14),
('Y13', 'Poisoning by and exposure to other and unspecified chemicals and noxious substances, undetermined intent', 14),
('Y14', 'Poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, undetermined intent', 14),
('Y15', 'Poisoning by and exposure to alcohol, undetermined intent', 14),
('Y18', 'Poisoning by and exposure to pesticides, undetermined intent', 14),
('Y20', 'Hanging, strangulation and suffocation, undetermined intent', 14),
('Y21', 'Drowning and submersion, undetermined intent', 14),
('Y22', 'Handgun discharge, undetermined intent', 14),
('Y24', 'Other and unspecified firearm discharge, undetermined intent', 14),
('Y25', 'Contact with explosive material, undetermined intent', 14),
('Y26', 'Exposure to smoke, fire and flames, undetermined intent', 14),
('Y28', 'Contact with sharp object, undetermined intent', 14),
('Y29', 'Contact with blunt object, undetermined intent', 14),
('Y30', 'Falling, jumping or pushed from a high place, undetermined intent', 14),
('Y31', 'Falling, lying or running before or into moving object, undetermined intent', 14),
('Y32', 'Crushing of motor vehicle, undetermined intent', 14),
('Y33', 'Other specified events ó e.g. electrocution, etc., undetermined intent', 14),
('Y34', 'Unspecified events, undetermined intent', 14),
('Y35', 'Legal intervention', 14),
('Y40', 'Systemic antibiotics causing adverse effects in therapeutic use', 14),
('Y41', 'Other systemic anti-infective and antiparasitics causing adverse effects in therapeutic use', 14),
('Y57', 'Other and unspecified drugs and medicaments causing adverse effects in therapeutic use', 14),
('P28', 'Other respiratory conditions originating in the perinatal period', 3);


/*
 * Add intervals to _web_assignment
 * */
alter table _web_assignment
add column c1_coda_time varchar(10),
add column c1_codb_time varchar(10),
add column c1_codc_time varchar(10),
add column c1_codd_time varchar(10),
add column c1_codcont_time varchar(10),
add column c2_coda_time varchar(10),
add column c2_codb_time varchar(10),
add column c2_codc_time varchar(10),
add column c2_codd_time varchar(10),
add column c2_codcont_time varchar(10),
add column c1_codcont integer,
add column c2_codcont integer;

/*
 *  Configure functions
 * */
CREATE FUNCTION returnUnderline(ca int, cb int, cc int, cd int) RETURNS integer AS $$
BEGIN
	IF cd IS NOT NULL THEN RETURN cd; END IF;
	IF cc IS NOT NULL THEN RETURN cc; END IF;
	IF cb IS NOT NULL THEN RETURN cb; END IF;
	IF ca IS NOT NULL THEN RETURN ca; ELSE RETURN NULL; END IF;
END; $$
LANGUAGE PLPGSQL;